file_format: "1"
id: dongle
name: DONGLE
type: shield
url: https://github.com/GEIGEIGEIST/TOTEM
requires: [seeeduino_xiao_ble]
features:
  - keys
siblings:
  - dongle_left
  - dongle_right
  - dongle_dongle
